### ISSUE TITLE
New Release and Nuget Version

### ISSUE THREAD

**Issue by delixfe** [tomaszeman/Xunit.Extensions.Ordering#5]
**Is your feature request related to a problem? Please describe.**
I would like to use the TestDependencyAttribute. But that functionality was never released. :). It would also be great to have the NetStandard2.0 version. 

**Describe the solution you'd like**
Please create a release and publish to NuGet.

**Describe alternatives you've considered**
You really do not want to know...

**Additional context**
Big thanks for creating that library.

**Comment by JDCain** [comment]
I added the code for the dependency ordering, but I don't know enough about the main project. I may end up releasing it separately to get it out there.

I can tell you there's an issue though with the dependency ordering and dotnet standard. The ex unit extensibility package it relies on does not restore correctly if it's in a dotnet standard project and the target that project is used in is classic dotnet. in order to work across all the versions it has to be set up to target all of them explicitly.

**Comment by JDCain** [comment]
@delixfe 
https://github.com/JDCain/Xunit.Extensions.TestDependency/releases/tag/1.0.0-preview.0

**Comment by delixfe** [comment]
Firstly, @JDCain thanks a million!
I am also using the AssemblyFixture from this package. As written in the readme, splitting the features into different packages would not easily work due to the orderers. Maybe we could address that issue with the XUnit team.

@tomaszeman Any chance of releasing or enabling @JDCain  to do so?

**Comment by tomaszeman** [comment]
Sorry, no time to manage this project, i will give you permission to anything you want 🤣 I made some refactoring and deeper dive into xunit but no time for release...

**Comment by JDCain** [comment]
@delixfe There is a separate assembly fixture package I use based on a package on here. I just had to clone it and build it for standard. https://www.nuget.org/packages/xunit.assemblyfixture/ If I get a chance I may fork it and see if I can publish a version

**Comment by JDCain** [comment]
@delixfe This may not be indexed yet but it should show shortly. Both packages just need their own Assembly reference. 
https://www.nuget.org/packages/Xunit.Extensions.AssemblyFixture/

AssemblyFixture extends Xunit.TestFramework
DepencenctyOrderer extends TestCaseOrderer
